server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  datasource:
    username: admin
    url: jdbc:h2:mem:testdb
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
  mvc:
   pathmatch:
    matching-strategy: ANT_PATH_MATCHER
  security:
       user:
          name: mj
          password: admin

jwt:
  secret: Um9iZXJ0QDIyMDU=